// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  ActionAcceptNewTaskMyNameActionTaskNewPostData,
  ActionAcceptNewTaskMyNameActionTaskNewPostErrors,
  ActionAcceptNewTaskMyNameActionTaskNewPostResponses,
  ActionBuyBankExpansionMyNameActionBankBuyExpansionPostData,
  ActionBuyBankExpansionMyNameActionBankBuyExpansionPostErrors,
  ActionBuyBankExpansionMyNameActionBankBuyExpansionPostResponses,
  ActionChangeSkinMyNameActionChangeSkinPostData,
  ActionChangeSkinMyNameActionChangeSkinPostErrors,
  ActionChangeSkinMyNameActionChangeSkinPostResponses,
  ActionCompleteTaskMyNameActionTaskCompletePostData,
  ActionCompleteTaskMyNameActionTaskCompletePostErrors,
  ActionCompleteTaskMyNameActionTaskCompletePostResponses,
  ActionCraftingMyNameActionCraftingPostData,
  ActionCraftingMyNameActionCraftingPostErrors,
  ActionCraftingMyNameActionCraftingPostResponses,
  ActionDeleteItemMyNameActionDeletePostData,
  ActionDeleteItemMyNameActionDeletePostErrors,
  ActionDeleteItemMyNameActionDeletePostResponses,
  ActionDepositBankGoldMyNameActionBankDepositGoldPostData,
  ActionDepositBankGoldMyNameActionBankDepositGoldPostErrors,
  ActionDepositBankGoldMyNameActionBankDepositGoldPostResponses,
  ActionDepositBankItemMyNameActionBankDepositItemPostData,
  ActionDepositBankItemMyNameActionBankDepositItemPostErrors,
  ActionDepositBankItemMyNameActionBankDepositItemPostResponses,
  ActionEquipItemMyNameActionEquipPostData,
  ActionEquipItemMyNameActionEquipPostErrors,
  ActionEquipItemMyNameActionEquipPostResponses,
  ActionFightMyNameActionFightPostData,
  ActionFightMyNameActionFightPostErrors,
  ActionFightMyNameActionFightPostResponses,
  ActionGatheringMyNameActionGatheringPostData,
  ActionGatheringMyNameActionGatheringPostErrors,
  ActionGatheringMyNameActionGatheringPostResponses,
  ActionGeBuyItemMyNameActionGrandexchangeBuyPostData,
  ActionGeBuyItemMyNameActionGrandexchangeBuyPostErrors,
  ActionGeBuyItemMyNameActionGrandexchangeBuyPostResponses,
  ActionGeCancelSellOrderMyNameActionGrandexchangeCancelPostData,
  ActionGeCancelSellOrderMyNameActionGrandexchangeCancelPostErrors,
  ActionGeCancelSellOrderMyNameActionGrandexchangeCancelPostResponses,
  ActionGeCreateSellOrderMyNameActionGrandexchangeSellPostData,
  ActionGeCreateSellOrderMyNameActionGrandexchangeSellPostErrors,
  ActionGeCreateSellOrderMyNameActionGrandexchangeSellPostResponses,
  ActionGiveGoldMyNameActionGiveGoldPostData,
  ActionGiveGoldMyNameActionGiveGoldPostErrors,
  ActionGiveGoldMyNameActionGiveGoldPostResponses,
  ActionGiveItemsMyNameActionGiveItemPostData,
  ActionGiveItemsMyNameActionGiveItemPostErrors,
  ActionGiveItemsMyNameActionGiveItemPostResponses,
  ActionMoveMyNameActionMovePostData,
  ActionMoveMyNameActionMovePostErrors,
  ActionMoveMyNameActionMovePostResponses,
  ActionNpcBuyItemMyNameActionNpcBuyPostData,
  ActionNpcBuyItemMyNameActionNpcBuyPostErrors,
  ActionNpcBuyItemMyNameActionNpcBuyPostResponses,
  ActionNpcSellItemMyNameActionNpcSellPostData,
  ActionNpcSellItemMyNameActionNpcSellPostErrors,
  ActionNpcSellItemMyNameActionNpcSellPostResponses,
  ActionRecyclingMyNameActionRecyclingPostData,
  ActionRecyclingMyNameActionRecyclingPostErrors,
  ActionRecyclingMyNameActionRecyclingPostResponses,
  ActionRestMyNameActionRestPostData,
  ActionRestMyNameActionRestPostErrors,
  ActionRestMyNameActionRestPostResponses,
  ActionTaskCancelMyNameActionTaskCancelPostData,
  ActionTaskCancelMyNameActionTaskCancelPostErrors,
  ActionTaskCancelMyNameActionTaskCancelPostResponses,
  ActionTaskExchangeMyNameActionTaskExchangePostData,
  ActionTaskExchangeMyNameActionTaskExchangePostErrors,
  ActionTaskExchangeMyNameActionTaskExchangePostResponses,
  ActionTaskTradeMyNameActionTaskTradePostData,
  ActionTaskTradeMyNameActionTaskTradePostErrors,
  ActionTaskTradeMyNameActionTaskTradePostResponses,
  ActionTransitionMyNameActionTransitionPostData,
  ActionTransitionMyNameActionTransitionPostErrors,
  ActionTransitionMyNameActionTransitionPostResponses,
  ActionUnequipItemMyNameActionUnequipPostData,
  ActionUnequipItemMyNameActionUnequipPostErrors,
  ActionUnequipItemMyNameActionUnequipPostResponses,
  ActionUseItemMyNameActionUsePostData,
  ActionUseItemMyNameActionUsePostErrors,
  ActionUseItemMyNameActionUsePostResponses,
  ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPostData,
  ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPostErrors,
  ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPostResponses,
  ActionWithdrawBankItemMyNameActionBankWithdrawItemPostData,
  ActionWithdrawBankItemMyNameActionBankWithdrawItemPostErrors,
  ActionWithdrawBankItemMyNameActionBankWithdrawItemPostResponses,
  ChangePasswordMyChangePasswordPostData,
  ChangePasswordMyChangePasswordPostErrors,
  ChangePasswordMyChangePasswordPostResponses,
  CreateAccountAccountsCreatePostData,
  CreateAccountAccountsCreatePostErrors,
  CreateAccountAccountsCreatePostResponses,
  CreateCharacterCharactersCreatePostData,
  CreateCharacterCharactersCreatePostErrors,
  CreateCharacterCharactersCreatePostResponses,
  DeleteCharacterCharactersDeletePostData,
  DeleteCharacterCharactersDeletePostErrors,
  DeleteCharacterCharactersDeletePostResponses,
  FightSimulationSimulationFightSimulationPostData,
  FightSimulationSimulationFightSimulationPostErrors,
  FightSimulationSimulationFightSimulationPostResponses,
  ForgotPasswordAccountsForgotPasswordPostData,
  ForgotPasswordAccountsForgotPasswordPostErrors,
  ForgotPasswordAccountsForgotPasswordPostResponses,
  GenerateTokenTokenPostData,
  GenerateTokenTokenPostErrors,
  GenerateTokenTokenPostResponses,
  GetAccountAccountsAccountGetData,
  GetAccountAccountsAccountGetErrors,
  GetAccountAccountsAccountGetResponses,
  GetAccountAchievementsAccountsAccountAchievementsGetData,
  GetAccountAchievementsAccountsAccountAchievementsGetErrors,
  GetAccountAchievementsAccountsAccountAchievementsGetResponses,
  GetAccountCharactersAccountsAccountCharactersGetData,
  GetAccountCharactersAccountsAccountCharactersGetResponses,
  GetAccountDetailsMyDetailsGetData,
  GetAccountDetailsMyDetailsGetResponses,
  GetAccountsLeaderboardLeaderboardAccountsGetData,
  GetAccountsLeaderboardLeaderboardAccountsGetResponses,
  GetAchievementAchievementsCodeGetData,
  GetAchievementAchievementsCodeGetErrors,
  GetAchievementAchievementsCodeGetResponses,
  GetActiveCharactersCharactersActiveGetData,
  GetActiveCharactersCharactersActiveGetResponses,
  GetAllAchievementsAchievementsGetData,
  GetAllAchievementsAchievementsGetResponses,
  GetAllActiveEventsEventsActiveGetData,
  GetAllActiveEventsEventsActiveGetResponses,
  GetAllBadgesBadgesGetData,
  GetAllBadgesBadgesGetResponses,
  GetAllCharactersLogsMyLogsGetData,
  GetAllCharactersLogsMyLogsGetErrors,
  GetAllCharactersLogsMyLogsGetResponses,
  GetAllEffectsEffectsGetData,
  GetAllEffectsEffectsGetResponses,
  GetAllEventsEventsGetData,
  GetAllEventsEventsGetResponses,
  GetAllItemsItemsGetData,
  GetAllItemsItemsGetResponses,
  GetAllMapsMapsGetData,
  GetAllMapsMapsGetResponses,
  GetAllMonstersMonstersGetData,
  GetAllMonstersMonstersGetResponses,
  GetAllNpcsItemsNpcsItemsGetData,
  GetAllNpcsItemsNpcsItemsGetResponses,
  GetAllNpcsNpcsDetailsGetData,
  GetAllNpcsNpcsDetailsGetResponses,
  GetAllResourcesResourcesGetData,
  GetAllResourcesResourcesGetResponses,
  GetAllTasksRewardsTasksRewardsGetData,
  GetAllTasksRewardsTasksRewardsGetResponses,
  GetAllTasksTasksListGetData,
  GetAllTasksTasksListGetResponses,
  GetBadgeBadgesCodeGetData,
  GetBadgeBadgesCodeGetErrors,
  GetBadgeBadgesCodeGetResponses,
  GetBankDetailsMyBankGetData,
  GetBankDetailsMyBankGetResponses,
  GetBankItemsMyBankItemsGetData,
  GetBankItemsMyBankItemsGetResponses,
  GetCharacterCharactersNameGetData,
  GetCharacterCharactersNameGetErrors,
  GetCharacterCharactersNameGetResponses,
  GetCharacterLogsMyLogsNameGetData,
  GetCharacterLogsMyLogsNameGetErrors,
  GetCharacterLogsMyLogsNameGetResponses,
  GetCharactersLeaderboardLeaderboardCharactersGetData,
  GetCharactersLeaderboardLeaderboardCharactersGetResponses,
  GetEffectEffectsCodeGetData,
  GetEffectEffectsCodeGetErrors,
  GetEffectEffectsCodeGetResponses,
  GetGeSellHistoryGrandexchangeHistoryCodeGetData,
  GetGeSellHistoryGrandexchangeHistoryCodeGetErrors,
  GetGeSellHistoryGrandexchangeHistoryCodeGetResponses,
  GetGeSellHistoryMyGrandexchangeHistoryGetData,
  GetGeSellHistoryMyGrandexchangeHistoryGetResponses,
  GetGeSellOrderGrandexchangeOrdersIdGetData,
  GetGeSellOrderGrandexchangeOrdersIdGetErrors,
  GetGeSellOrderGrandexchangeOrdersIdGetResponses,
  GetGeSellOrdersGrandexchangeOrdersGetData,
  GetGeSellOrdersGrandexchangeOrdersGetResponses,
  GetGeSellOrdersMyGrandexchangeOrdersGetData,
  GetGeSellOrdersMyGrandexchangeOrdersGetResponses,
  GetItemItemsCodeGetData,
  GetItemItemsCodeGetErrors,
  GetItemItemsCodeGetResponses,
  GetLayerMapsMapsLayerGetData,
  GetLayerMapsMapsLayerGetResponses,
  GetMapByIdMapsIdMapIdGetData,
  GetMapByIdMapsIdMapIdGetErrors,
  GetMapByIdMapsIdMapIdGetResponses,
  GetMapByPositionMapsLayerXyGetData,
  GetMapByPositionMapsLayerXyGetErrors,
  GetMapByPositionMapsLayerXyGetResponses,
  GetMonsterMonstersCodeGetData,
  GetMonsterMonstersCodeGetErrors,
  GetMonsterMonstersCodeGetResponses,
  GetMyCharactersMyCharactersGetData,
  GetMyCharactersMyCharactersGetResponses,
  GetNpcItemsNpcsItemsCodeGetData,
  GetNpcItemsNpcsItemsCodeGetErrors,
  GetNpcItemsNpcsItemsCodeGetResponses,
  GetNpcNpcsDetailsCodeGetData,
  GetNpcNpcsDetailsCodeGetErrors,
  GetNpcNpcsDetailsCodeGetResponses,
  GetResourceResourcesCodeGetData,
  GetResourceResourcesCodeGetErrors,
  GetResourceResourcesCodeGetResponses,
  GetServerDetailsGetData,
  GetServerDetailsGetResponses,
  GetTasksRewardTasksRewardsCodeGetData,
  GetTasksRewardTasksRewardsCodeGetErrors,
  GetTasksRewardTasksRewardsCodeGetResponses,
  GetTaskTasksListCodeGetData,
  GetTaskTasksListCodeGetErrors,
  GetTaskTasksListCodeGetResponses,
  ResetPasswordAccountsResetPasswordPostData,
  ResetPasswordAccountsResetPasswordPostErrors,
  ResetPasswordAccountsResetPasswordPostResponses,
  SpawnEventEventsSpawnPostData,
  SpawnEventEventsSpawnPostErrors,
  SpawnEventEventsSpawnPostResponses,
} from './types.gen'

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Get Server Details
 *
 * Return the status of the game server.
 */
export const getServerDetailsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetServerDetailsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetServerDetailsGetResponses, unknown, ThrowOnError>({
    url: '/',
    ...options,
  })
}

/**
 * Get Bank Details
 *
 * Fetch bank details.
 */
export const getBankDetailsMyBankGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetBankDetailsMyBankGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetBankDetailsMyBankGetResponses, unknown, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/bank',
    ...options,
  })
}

/**
 * Get Bank Items
 *
 * Fetch all items in your bank.
 */
export const getBankItemsMyBankItemsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetBankItemsMyBankItemsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetBankItemsMyBankItemsGetResponses, unknown, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/bank/items',
    ...options,
  })
}

/**
 * Get Ge Sell Orders
 *
 * Fetch your sell orders details.
 */
export const getGeSellOrdersMyGrandexchangeOrdersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetGeSellOrdersMyGrandexchangeOrdersGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetGeSellOrdersMyGrandexchangeOrdersGetResponses, unknown, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/grandexchange/orders',
    ...options,
  })
}

/**
 * Get Ge Sell History
 *
 * Fetch your sales history of the last 7 days.
 */
export const getGeSellHistoryMyGrandexchangeHistoryGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetGeSellHistoryMyGrandexchangeHistoryGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetGeSellHistoryMyGrandexchangeHistoryGetResponses, unknown, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/grandexchange/history',
    ...options,
  })
}

/**
 * Get Account Details
 *
 * Fetch account details.
 */
export const getAccountDetailsMyDetailsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAccountDetailsMyDetailsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAccountDetailsMyDetailsGetResponses, unknown, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/details',
    ...options,
  })
}

/**
 * Change Password
 *
 * Change your account password. Changing the password reset the account token.
 */
export const changePasswordMyChangePasswordPost = <ThrowOnError extends boolean = false>(
  options: Options<ChangePasswordMyChangePasswordPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ChangePasswordMyChangePasswordPostResponses,
    ChangePasswordMyChangePasswordPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/change_password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Move
 *
 * Moves a character on the map using either the map's ID or X and Y position.
 * Provide either 'map_id' or both 'x' and 'y' coordinates in the request body.
 */
export const actionMoveMyNameActionMovePost = <ThrowOnError extends boolean = false>(
  options: Options<ActionMoveMyNameActionMovePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionMoveMyNameActionMovePostResponses,
    ActionMoveMyNameActionMovePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/move',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Transition
 *
 * Execute a transition from the current map to another layer.
 * The character must be on a map that has a transition available.
 */
export const actionTransitionMyNameActionTransitionPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionTransitionMyNameActionTransitionPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionTransitionMyNameActionTransitionPostResponses,
    ActionTransitionMyNameActionTransitionPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/transition',
    ...options,
  })
}

/**
 * Action Rest
 *
 * Recovers hit points by resting. (1 second per 5 HP, minimum 3 seconds)
 */
export const actionRestMyNameActionRestPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionRestMyNameActionRestPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionRestMyNameActionRestPostResponses,
    ActionRestMyNameActionRestPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/rest',
    ...options,
  })
}

/**
 * Action Equip Item
 *
 * Equip an item on your character.
 */
export const actionEquipItemMyNameActionEquipPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionEquipItemMyNameActionEquipPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionEquipItemMyNameActionEquipPostResponses,
    ActionEquipItemMyNameActionEquipPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/equip',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Unequip Item
 *
 * Unequip an item on your character.
 */
export const actionUnequipItemMyNameActionUnequipPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionUnequipItemMyNameActionUnequipPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionUnequipItemMyNameActionUnequipPostResponses,
    ActionUnequipItemMyNameActionUnequipPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/unequip',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Use Item
 *
 * Use an item as a consumable.
 */
export const actionUseItemMyNameActionUsePost = <ThrowOnError extends boolean = false>(
  options: Options<ActionUseItemMyNameActionUsePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionUseItemMyNameActionUsePostResponses,
    ActionUseItemMyNameActionUsePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/use',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Fight
 *
 * Start a fight against a monster on the character's map.
 * Add participants for multi-character fights (up to 3 characters, only for boss).
 */
export const actionFightMyNameActionFightPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionFightMyNameActionFightPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionFightMyNameActionFightPostResponses,
    ActionFightMyNameActionFightPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/fight',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Gathering
 *
 * Harvest a resource on the character's map.
 */
export const actionGatheringMyNameActionGatheringPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionGatheringMyNameActionGatheringPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionGatheringMyNameActionGatheringPostResponses,
    ActionGatheringMyNameActionGatheringPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/gathering',
    ...options,
  })
}

/**
 * Action Crafting
 *
 * Craft an item. The character must be on a map with a workshop.
 */
export const actionCraftingMyNameActionCraftingPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionCraftingMyNameActionCraftingPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionCraftingMyNameActionCraftingPostResponses,
    ActionCraftingMyNameActionCraftingPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/crafting',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Deposit Bank Gold
 *
 * Deposit gold in a bank on the character's map.
 */
export const actionDepositBankGoldMyNameActionBankDepositGoldPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionDepositBankGoldMyNameActionBankDepositGoldPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionDepositBankGoldMyNameActionBankDepositGoldPostResponses,
    ActionDepositBankGoldMyNameActionBankDepositGoldPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/bank/deposit/gold',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Deposit Bank Item
 *
 * Deposit multiple items in a bank on the character's map.
 * The cooldown will be 3 seconds multiplied by the number of different items deposited.
 */
export const actionDepositBankItemMyNameActionBankDepositItemPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionDepositBankItemMyNameActionBankDepositItemPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionDepositBankItemMyNameActionBankDepositItemPostResponses,
    ActionDepositBankItemMyNameActionBankDepositItemPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/bank/deposit/item',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Withdraw Bank Item
 *
 * Take items from your bank and put them in the character's inventory.
 * The cooldown will be 3 seconds multiplied by the number of different items withdrawn.
 */
export const actionWithdrawBankItemMyNameActionBankWithdrawItemPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionWithdrawBankItemMyNameActionBankWithdrawItemPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionWithdrawBankItemMyNameActionBankWithdrawItemPostResponses,
    ActionWithdrawBankItemMyNameActionBankWithdrawItemPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/bank/withdraw/item',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Withdraw Bank Gold
 *
 * Withdraw gold from your bank.
 */
export const actionWithdrawBankGoldMyNameActionBankWithdrawGoldPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPostResponses,
    ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/bank/withdraw/gold',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Buy Bank Expansion
 *
 * Buy a 20 slots bank expansion.
 */
export const actionBuyBankExpansionMyNameActionBankBuyExpansionPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionBuyBankExpansionMyNameActionBankBuyExpansionPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionBuyBankExpansionMyNameActionBankBuyExpansionPostResponses,
    ActionBuyBankExpansionMyNameActionBankBuyExpansionPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/bank/buy_expansion',
    ...options,
  })
}

/**
 * Action Npc Buy Item
 *
 * Buy an item from an NPC on the character's map.
 */
export const actionNpcBuyItemMyNameActionNpcBuyPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionNpcBuyItemMyNameActionNpcBuyPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionNpcBuyItemMyNameActionNpcBuyPostResponses,
    ActionNpcBuyItemMyNameActionNpcBuyPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/npc/buy',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Npc Sell Item
 *
 * Sell an item to an NPC on the character's map.
 */
export const actionNpcSellItemMyNameActionNpcSellPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionNpcSellItemMyNameActionNpcSellPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionNpcSellItemMyNameActionNpcSellPostResponses,
    ActionNpcSellItemMyNameActionNpcSellPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/npc/sell',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Recycling
 *
 * Recycling an item. The character must be on a map with a workshop (only for equipments and weapons).
 */
export const actionRecyclingMyNameActionRecyclingPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionRecyclingMyNameActionRecyclingPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionRecyclingMyNameActionRecyclingPostResponses,
    ActionRecyclingMyNameActionRecyclingPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/recycling',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Ge Buy Item
 *
 * Buy an item at the Grand Exchange on the character's map.
 */
export const actionGeBuyItemMyNameActionGrandexchangeBuyPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionGeBuyItemMyNameActionGrandexchangeBuyPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionGeBuyItemMyNameActionGrandexchangeBuyPostResponses,
    ActionGeBuyItemMyNameActionGrandexchangeBuyPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/grandexchange/buy',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Ge Create Sell Order
 *
 * Create a sell order at the Grand Exchange on the character's map.
 * Please note there is a 3% listing tax, charged at the time of posting, on the total price.
 */
export const actionGeCreateSellOrderMyNameActionGrandexchangeSellPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionGeCreateSellOrderMyNameActionGrandexchangeSellPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionGeCreateSellOrderMyNameActionGrandexchangeSellPostResponses,
    ActionGeCreateSellOrderMyNameActionGrandexchangeSellPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/grandexchange/sell',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Ge Cancel Sell Order
 *
 * Cancel a sell order at the Grand Exchange on the character's map.
 */
export const actionGeCancelSellOrderMyNameActionGrandexchangeCancelPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionGeCancelSellOrderMyNameActionGrandexchangeCancelPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionGeCancelSellOrderMyNameActionGrandexchangeCancelPostResponses,
    ActionGeCancelSellOrderMyNameActionGrandexchangeCancelPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/grandexchange/cancel',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Complete Task
 *
 * Complete a task.
 */
export const actionCompleteTaskMyNameActionTaskCompletePost = <ThrowOnError extends boolean = false>(
  options: Options<ActionCompleteTaskMyNameActionTaskCompletePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionCompleteTaskMyNameActionTaskCompletePostResponses,
    ActionCompleteTaskMyNameActionTaskCompletePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/task/complete',
    ...options,
  })
}

/**
 * Action Task Exchange
 *
 * Exchange 6 tasks coins for a random reward. Rewards are exclusive items or resources.
 */
export const actionTaskExchangeMyNameActionTaskExchangePost = <ThrowOnError extends boolean = false>(
  options: Options<ActionTaskExchangeMyNameActionTaskExchangePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionTaskExchangeMyNameActionTaskExchangePostResponses,
    ActionTaskExchangeMyNameActionTaskExchangePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/task/exchange',
    ...options,
  })
}

/**
 * Action Accept New Task
 *
 * Accepting a new task.
 */
export const actionAcceptNewTaskMyNameActionTaskNewPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionAcceptNewTaskMyNameActionTaskNewPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionAcceptNewTaskMyNameActionTaskNewPostResponses,
    ActionAcceptNewTaskMyNameActionTaskNewPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/task/new',
    ...options,
  })
}

/**
 * Action Task Trade
 *
 * Trading items with a Tasks Master.
 */
export const actionTaskTradeMyNameActionTaskTradePost = <ThrowOnError extends boolean = false>(
  options: Options<ActionTaskTradeMyNameActionTaskTradePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionTaskTradeMyNameActionTaskTradePostResponses,
    ActionTaskTradeMyNameActionTaskTradePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/task/trade',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Task Cancel
 *
 * Cancel a task for 1 tasks coin.
 */
export const actionTaskCancelMyNameActionTaskCancelPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionTaskCancelMyNameActionTaskCancelPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionTaskCancelMyNameActionTaskCancelPostResponses,
    ActionTaskCancelMyNameActionTaskCancelPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/task/cancel',
    ...options,
  })
}

/**
 * Action Give Gold
 *
 * Give gold to another character in your account on the same map.
 */
export const actionGiveGoldMyNameActionGiveGoldPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionGiveGoldMyNameActionGiveGoldPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionGiveGoldMyNameActionGiveGoldPostResponses,
    ActionGiveGoldMyNameActionGiveGoldPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/give/gold',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Give Items
 *
 * Give items to another character in your account on the same map.
 * The cooldown will be 3 seconds multiplied by the number of different items given.
 */
export const actionGiveItemsMyNameActionGiveItemPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionGiveItemsMyNameActionGiveItemPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionGiveItemsMyNameActionGiveItemPostResponses,
    ActionGiveItemsMyNameActionGiveItemPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/give/item',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Delete Item
 *
 * Delete an item from your character's inventory.
 */
export const actionDeleteItemMyNameActionDeletePost = <ThrowOnError extends boolean = false>(
  options: Options<ActionDeleteItemMyNameActionDeletePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionDeleteItemMyNameActionDeletePostResponses,
    ActionDeleteItemMyNameActionDeletePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Action Change Skin
 *
 * Change the skin of your character.
 */
export const actionChangeSkinMyNameActionChangeSkinPost = <ThrowOnError extends boolean = false>(
  options: Options<ActionChangeSkinMyNameActionChangeSkinPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionChangeSkinMyNameActionChangeSkinPostResponses,
    ActionChangeSkinMyNameActionChangeSkinPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/{name}/action/change_skin',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get All Characters Logs
 *
 * History of the last 5000 actions of all your characters.
 */
export const getAllCharactersLogsMyLogsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllCharactersLogsMyLogsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllCharactersLogsMyLogsGetResponses,
    GetAllCharactersLogsMyLogsGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/logs',
    ...options,
  })
}

/**
 * Get Character Logs
 *
 * History of the last actions of your character.
 */
export const getCharacterLogsMyLogsNameGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCharacterLogsMyLogsNameGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetCharacterLogsMyLogsNameGetResponses,
    GetCharacterLogsMyLogsNameGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/logs/{name}',
    ...options,
  })
}

/**
 * Get My Characters
 *
 * List of your characters.
 */
export const getMyCharactersMyCharactersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMyCharactersMyCharactersGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetMyCharactersMyCharactersGetResponses, unknown, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/my/characters',
    ...options,
  })
}

/**
 * Create Account
 */
export const createAccountAccountsCreatePost = <ThrowOnError extends boolean = false>(
  options: Options<CreateAccountAccountsCreatePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateAccountAccountsCreatePostResponses,
    CreateAccountAccountsCreatePostErrors,
    ThrowOnError
  >({
    url: '/accounts/create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Forgot Password
 *
 * Request a password reset.
 */
export const forgotPasswordAccountsForgotPasswordPost = <ThrowOnError extends boolean = false>(
  options: Options<ForgotPasswordAccountsForgotPasswordPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ForgotPasswordAccountsForgotPasswordPostResponses,
    ForgotPasswordAccountsForgotPasswordPostErrors,
    ThrowOnError
  >({
    url: '/accounts/forgot_password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Reset Password
 *
 * Reset password with a token. Use /forgot_password to get a token by email.
 */
export const resetPasswordAccountsResetPasswordPost = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordAccountsResetPasswordPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetPasswordAccountsResetPasswordPostResponses,
    ResetPasswordAccountsResetPasswordPostErrors,
    ThrowOnError
  >({
    url: '/accounts/reset_password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Account Achievements
 *
 * Retrieve the achievements of a account.
 */
export const getAccountAchievementsAccountsAccountAchievementsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountAchievementsAccountsAccountAchievementsGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAccountAchievementsAccountsAccountAchievementsGetResponses,
    GetAccountAchievementsAccountsAccountAchievementsGetErrors,
    ThrowOnError
  >({
    url: '/accounts/{account}/achievements',
    ...options,
  })
}

/**
 * Get Account Characters
 *
 * Account character lists.
 */
export const getAccountCharactersAccountsAccountCharactersGet = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountCharactersAccountsAccountCharactersGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAccountCharactersAccountsAccountCharactersGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/accounts/{account}/characters',
    ...options,
  })
}

/**
 * Get Account
 *
 * Retrieve the details of an account.
 */
export const getAccountAccountsAccountGet = <ThrowOnError extends boolean = false>(
  options: Options<GetAccountAccountsAccountGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAccountAccountsAccountGetResponses,
    GetAccountAccountsAccountGetErrors,
    ThrowOnError
  >({
    url: '/accounts/{account}',
    ...options,
  })
}

/**
 * Get All Achievements
 *
 * List of all achievements.
 */
export const getAllAchievementsAchievementsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllAchievementsAchievementsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllAchievementsAchievementsGetResponses, unknown, ThrowOnError>({
    url: '/achievements',
    ...options,
  })
}

/**
 * Get Achievement
 *
 * Retrieve the details of an achievement.
 */
export const getAchievementAchievementsCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetAchievementAchievementsCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAchievementAchievementsCodeGetResponses,
    GetAchievementAchievementsCodeGetErrors,
    ThrowOnError
  >({
    url: '/achievements/{code}',
    ...options,
  })
}

/**
 * Get All Badges
 *
 * List of all badges.
 */
export const getAllBadgesBadgesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllBadgesBadgesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllBadgesBadgesGetResponses, unknown, ThrowOnError>({
    url: '/badges',
    ...options,
  })
}

/**
 * Get Badge
 *
 * Retrieve the details of a badge.
 */
export const getBadgeBadgesCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetBadgeBadgesCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetBadgeBadgesCodeGetResponses, GetBadgeBadgesCodeGetErrors, ThrowOnError>({
    url: '/badges/{code}',
    ...options,
  })
}

/**
 * Create Character
 *
 * Create new character on your account. You can create up to 5 characters.
 */
export const createCharacterCharactersCreatePost = <ThrowOnError extends boolean = false>(
  options: Options<CreateCharacterCharactersCreatePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateCharacterCharactersCreatePostResponses,
    CreateCharacterCharactersCreatePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/characters/create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Delete Character
 *
 * Delete character on your account.
 */
export const deleteCharacterCharactersDeletePost = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCharacterCharactersDeletePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    DeleteCharacterCharactersDeletePostResponses,
    DeleteCharacterCharactersDeletePostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/characters/delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Active Characters
 *
 * Fetch active characters details.
 */
export const getActiveCharactersCharactersActiveGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetActiveCharactersCharactersActiveGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetActiveCharactersCharactersActiveGetResponses, unknown, ThrowOnError>({
    url: '/characters/active',
    ...options,
  })
}

/**
 * Get Character
 *
 * Retrieve the details of a character.
 */
export const getCharacterCharactersNameGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCharacterCharactersNameGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetCharacterCharactersNameGetResponses,
    GetCharacterCharactersNameGetErrors,
    ThrowOnError
  >({
    url: '/characters/{name}',
    ...options,
  })
}

/**
 * Get All Effects
 *
 * List of all effects. Effects are used by equipment, tools, runes, consumables and monsters. An effect is an action that produces an effect on the game.
 */
export const getAllEffectsEffectsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllEffectsEffectsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllEffectsEffectsGetResponses, unknown, ThrowOnError>({
    url: '/effects',
    ...options,
  })
}

/**
 * Get Effect
 *
 * Retrieve the details of an effect.
 */
export const getEffectEffectsCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetEffectEffectsCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetEffectEffectsCodeGetResponses, GetEffectEffectsCodeGetErrors, ThrowOnError>({
    url: '/effects/{code}',
    ...options,
  })
}

/**
 * Get All Active Events
 *
 * Fetch active events details.
 */
export const getAllActiveEventsEventsActiveGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllActiveEventsEventsActiveGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllActiveEventsEventsActiveGetResponses, unknown, ThrowOnError>({
    url: '/events/active',
    ...options,
  })
}

/**
 * Get All Events
 *
 * Fetch events details.
 */
export const getAllEventsEventsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllEventsEventsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllEventsEventsGetResponses, unknown, ThrowOnError>({
    url: '/events',
    ...options,
  })
}

/**
 * Spawn Event
 *
 * Spawn a specific event by code consuming 1 event token.
 *
 * Rules:
 * - Maximum active events defined by utils.config.max_active_events().
 * - Event must not already be active.
 * - Member or founder account required.
 */
export const spawnEventEventsSpawnPost = <ThrowOnError extends boolean = false>(
  options: Options<SpawnEventEventsSpawnPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SpawnEventEventsSpawnPostResponses,
    SpawnEventEventsSpawnPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/events/spawn',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Ge Sell History
 *
 * Fetch the sales history of the item for the last 7 days.
 */
export const getGeSellHistoryGrandexchangeHistoryCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetGeSellHistoryGrandexchangeHistoryCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetGeSellHistoryGrandexchangeHistoryCodeGetResponses,
    GetGeSellHistoryGrandexchangeHistoryCodeGetErrors,
    ThrowOnError
  >({
    url: '/grandexchange/history/{code}',
    ...options,
  })
}

/**
 * Get Ge Sell Orders
 *
 * Fetch all sell orders.
 */
export const getGeSellOrdersGrandexchangeOrdersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetGeSellOrdersGrandexchangeOrdersGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetGeSellOrdersGrandexchangeOrdersGetResponses, unknown, ThrowOnError>({
    url: '/grandexchange/orders',
    ...options,
  })
}

/**
 * Get Ge Sell Order
 *
 * Retrieve the sell order of a item.
 */
export const getGeSellOrderGrandexchangeOrdersIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetGeSellOrderGrandexchangeOrdersIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetGeSellOrderGrandexchangeOrdersIdGetResponses,
    GetGeSellOrderGrandexchangeOrdersIdGetErrors,
    ThrowOnError
  >({
    url: '/grandexchange/orders/{id}',
    ...options,
  })
}

/**
 * Get All Items
 *
 * Fetch items details.
 */
export const getAllItemsItemsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllItemsItemsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllItemsItemsGetResponses, unknown, ThrowOnError>({
    url: '/items',
    ...options,
  })
}

/**
 * Get Item
 *
 * Retrieve the details of a item.
 */
export const getItemItemsCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetItemItemsCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetItemItemsCodeGetResponses, GetItemItemsCodeGetErrors, ThrowOnError>({
    url: '/items/{code}',
    ...options,
  })
}

/**
 * Get Characters Leaderboard
 *
 * Fetch leaderboard details.
 */
export const getCharactersLeaderboardLeaderboardCharactersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetCharactersLeaderboardLeaderboardCharactersGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCharactersLeaderboardLeaderboardCharactersGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/leaderboard/characters',
    ...options,
  })
}

/**
 * Get Accounts Leaderboard
 *
 * Fetch leaderboard details.
 */
export const getAccountsLeaderboardLeaderboardAccountsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAccountsLeaderboardLeaderboardAccountsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAccountsLeaderboardLeaderboardAccountsGetResponses, unknown, ThrowOnError>({
    url: '/leaderboard/accounts',
    ...options,
  })
}

/**
 * Get All Maps
 *
 * Fetch maps details.
 */
export const getAllMapsMapsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllMapsMapsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllMapsMapsGetResponses, unknown, ThrowOnError>({
    url: '/maps',
    ...options,
  })
}

/**
 * Get Layer Maps
 *
 * Fetch maps details.
 */
export const getLayerMapsMapsLayerGet = <ThrowOnError extends boolean = false>(
  options: Options<GetLayerMapsMapsLayerGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetLayerMapsMapsLayerGetResponses, unknown, ThrowOnError>({
    url: '/maps/{layer}',
    ...options,
  })
}

/**
 * Get Map By Position
 *
 * Retrieve the details of a map by layer and coordinates.
 */
export const getMapByPositionMapsLayerXYGet = <ThrowOnError extends boolean = false>(
  options: Options<GetMapByPositionMapsLayerXyGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetMapByPositionMapsLayerXyGetResponses,
    GetMapByPositionMapsLayerXyGetErrors,
    ThrowOnError
  >({
    url: '/maps/{layer}/{x}/{y}',
    ...options,
  })
}

/**
 * Get Map By Id
 *
 * Retrieve the details of a map by its unique ID.
 */
export const getMapByIdMapsIdMapIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetMapByIdMapsIdMapIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetMapByIdMapsIdMapIdGetResponses,
    GetMapByIdMapsIdMapIdGetErrors,
    ThrowOnError
  >({
    url: '/maps/id/{map_id}',
    ...options,
  })
}

/**
 * Get All Monsters
 *
 * Fetch monsters details.
 */
export const getAllMonstersMonstersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllMonstersMonstersGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllMonstersMonstersGetResponses, unknown, ThrowOnError>({
    url: '/monsters',
    ...options,
  })
}

/**
 * Get Monster
 *
 * Retrieve the details of a monster.
 */
export const getMonsterMonstersCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetMonsterMonstersCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetMonsterMonstersCodeGetResponses,
    GetMonsterMonstersCodeGetErrors,
    ThrowOnError
  >({
    url: '/monsters/{code}',
    ...options,
  })
}

/**
 * Get All Npcs
 *
 * Fetch NPCs details.
 */
export const getAllNpcsNpcsDetailsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllNpcsNpcsDetailsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllNpcsNpcsDetailsGetResponses, unknown, ThrowOnError>({
    url: '/npcs/details',
    ...options,
  })
}

/**
 * Get Npc
 *
 * Retrieve the details of a NPC.
 */
export const getNpcNpcsDetailsCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetNpcNpcsDetailsCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetNpcNpcsDetailsCodeGetResponses,
    GetNpcNpcsDetailsCodeGetErrors,
    ThrowOnError
  >({
    url: '/npcs/details/{code}',
    ...options,
  })
}

/**
 * Get Npc Items
 *
 * Retrieve the items list of a NPC. If the NPC has items to buy, sell or trade, they will be displayed.
 */
export const getNpcItemsNpcsItemsCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetNpcItemsNpcsItemsCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetNpcItemsNpcsItemsCodeGetResponses,
    GetNpcItemsNpcsItemsCodeGetErrors,
    ThrowOnError
  >({
    url: '/npcs/items/{code}',
    ...options,
  })
}

/**
 * Get All Npcs Items
 *
 * Retrieve the list of all NPC items.
 */
export const getAllNpcsItemsNpcsItemsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllNpcsItemsNpcsItemsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllNpcsItemsNpcsItemsGetResponses, unknown, ThrowOnError>({
    url: '/npcs/items',
    ...options,
  })
}

/**
 * Get All Resources
 *
 * Fetch resources details.
 */
export const getAllResourcesResourcesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllResourcesResourcesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllResourcesResourcesGetResponses, unknown, ThrowOnError>({
    url: '/resources',
    ...options,
  })
}

/**
 * Get Resource
 *
 * Retrieve the details of a resource.
 */
export const getResourceResourcesCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetResourceResourcesCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetResourceResourcesCodeGetResponses,
    GetResourceResourcesCodeGetErrors,
    ThrowOnError
  >({
    url: '/resources/{code}',
    ...options,
  })
}

/**
 * Get All Tasks
 *
 * Fetch the list of all tasks.
 */
export const getAllTasksTasksListGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllTasksTasksListGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllTasksTasksListGetResponses, unknown, ThrowOnError>({
    url: '/tasks/list',
    ...options,
  })
}

/**
 * Get Task
 *
 * Retrieve the details of a task.
 */
export const getTaskTasksListCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTaskTasksListCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetTaskTasksListCodeGetResponses, GetTaskTasksListCodeGetErrors, ThrowOnError>({
    url: '/tasks/list/{code}',
    ...options,
  })
}

/**
 * Get All Tasks Rewards
 *
 * Fetch the list of all tasks rewards. To obtain these rewards, you must exchange 6 task coins with a tasks master.
 */
export const getAllTasksRewardsTasksRewardsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllTasksRewardsTasksRewardsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetAllTasksRewardsTasksRewardsGetResponses, unknown, ThrowOnError>({
    url: '/tasks/rewards',
    ...options,
  })
}

/**
 * Get Tasks Reward
 *
 * Retrieve the details of a tasks reward.
 */
export const getTasksRewardTasksRewardsCodeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTasksRewardTasksRewardsCodeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetTasksRewardTasksRewardsCodeGetResponses,
    GetTasksRewardTasksRewardsCodeGetErrors,
    ThrowOnError
  >({
    url: '/tasks/rewards/{code}',
    ...options,
  })
}

/**
 * Fight Simulation
 *
 * Simulate combat with fake characters against a monster multiple times.
 * Member or founder account required.
 */
export const fightSimulationSimulationFightSimulationPost = <ThrowOnError extends boolean = false>(
  options: Options<FightSimulationSimulationFightSimulationPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    FightSimulationSimulationFightSimulationPostResponses,
    FightSimulationSimulationFightSimulationPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/simulation/fight_simulation',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Generate Token
 *
 * Use your account as HTTPBasic Auth to generate your token to use the API. You can also generate your token directly on the website.
 */
export const generateTokenTokenPost = <ThrowOnError extends boolean = false>(
  options?: Options<GenerateTokenTokenPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<GenerateTokenTokenPostResponses, GenerateTokenTokenPostErrors, ThrowOnError>({
    security: [
      {
        scheme: 'basic',
        type: 'http',
      },
    ],
    url: '/token',
    ...options,
  })
}
